services:
  db:
    image: postgres:16-alpine
    container_name: expense-postgres
    environment:
      POSTGRES_USER: abd
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: expense_tracker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "abd"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
