spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/expense_tracker
    username: abd
    password: secret

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8081
  address: 0.0.0.0

springdoc:
  swagger-ui:
    path: /swagger